# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/sshinelt/ide/electron-ide
      services:
        - vscode
        - docker
      stages:
        - name: config-npm
          script: npm config set registry https://mirrors.cloud.tencent.com/npm
        - name: install-package
          script: npm install -g pnpm && pnpm config set store-dir ~/.pnpm-store && pnpm i
        - name: install-vscode-codebuddy
          script: code-server --install-extension tencent-cloud.coding-copilot
        - name: install-codegraph
          script: npm i -g @colbymchenry/codegraph && codegraph init -i && mkdir -p /root/.codebuddy && cp .codebuddy/mcp.json  /root/.codebuddy/
        - name: install-idea-plugin
          script: /ide_cnb/idea-IU-**/bin/idea.sh installPlugins com.tencent.cloud.codingcopilot
master:
  push:
    - docker:
        image: electronuserland/builder:wine
      env:
        BACKEND_NAME: annotation-manager-pc
        PROJECT_PATH: /opt/1panel/apps/openresty/openresty/www/sites/at.sshine.ltd/index
      services:
        - docker
      imports:
        - https://cnb.cool/sshinelt/secret/-/blob/main/154.36.173.172.yml
      stages:
        - name: 安装依赖
          script: |
            npm config set registry https://mirrors.cloud.tencent.com/npm
            npm install -g pnpm && pnpm i
        - name: 构建
          script: |
            rm -rf release
            pnpm build -wl
            cp download.html release/
            cp changelog.json release/
            tar -vczf release.tar.gz $(find release -maxdepth 2  -type f \( -name "*.exe" -o -name "*.deb" -o -name "*.AppImage" \)) release/*/latest*.yml release/download.html release/changelog.json
        - name: 上传附件
          image: docker.cnb.cool/sshinelt/cnb-tool/sftp-tool
          settings:
            ssh_host: $SEC_HOST
            ssh_user: $SEC_USERNAME
            ssh_password: $SEC_PASSWORD
            local_file_path: release.tar.gz
            remote_file_path: /tmp/release.tar.gz
        - name: 远程部署
          image: cnbcool/ssh
          settings:
            host: $SEC_HOST
            port: 22
            username: $SEC_USERNAME
            password: $SEC_PASSWORD
            script: |
              rm -rf ${PROJECT_PATH}/**
              tar -vxzf /tmp/release.tar.gz -C ${PROJECT_PATH}/
              mv ${PROJECT_PATH}/release/*/* ${PROJECT_PATH}/
              mv ${PROJECT_PATH}/release/download.html ${PROJECT_PATH}/
              mv ${PROJECT_PATH}/release/changelog.json ${PROJECT_PATH}/
              rm -rf ${PROJECT_PATH}/release
              rm -rf /tmp/release.tar.gz
        - name: 同步到GitHub
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/xiaoguokf/annotation-manager-pc.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: master
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}
